### PR TITLE
Buffer size adjustments for real-time audio notifiers

### PR DESCRIPTION
**Pull request by dcerisano**
Thanks for the great work getting node-speaker working properly on win32.

The original TooTallNate repo  closes child IPC channels only on win32 when called from a spawned process (linux just works). Your version does not disconnect prematurely. Did not have time to determine which of your changes fixed it, but thanks. Perhaps we could work together push the required changes to Nate's repo.

I had to further reduce your alsa and win32 audio buffers in order to get real time audio notifiers working smoothly with no stuttering or blocking during buffering. This allows bursts of audio notifiers to proceed without blocking each other.

That is the only use case I am concerned with, so this pull request should be tested in other use cases (HD audio streaming, etc) before being accepted. Really need a dynamic solution that allows for user configurable buffers.

### CODE REVIEW

**Comment by colinbdclark** [comment]
Hi @dcerisano, thanks for sharing your feedback, it's nice to hear that this fork was useful for you. I assembled this from various pull requests to the upstream library that hadn't been merged—it seems that node-speaker is not well maintained these days, along with my own similar tweaks to the buffer size on various platforms.

Unfortunately Flocking (the library that I used this for in the past) no longer supports Node.js. My feeling was, at the time, that there really wasn't a sufficiently robust audio output module for Node.js. In particular, the use of mpg123 in node-speakeras the backend library is probably really not viable, as changes like we've made really should be user-configurable. Have you looked at any of the more modern audio modules for Node.js such as naudiodon or libao?

Given that this was just a fork for local changes to node-speaker, and not a library I maintain or use, I'm not sure there's much advantage to me merging your changes here. Maybe the upstream project is more responsive these days and would take these changes?

**Comment by dcerisano** [comment]
`node-speaker` is still very popular at over 3000 npm  downloads per week, and getting more popular.
I was sucked in by these user stats, and have regretted it since. It is not thread-safe or even re-entrant and leaks massive amounts of memory if called too frequently.

I looked into `libao` and `naudion` but they did not seem to have a very large user base. I am suspecting this because trying to do robust audio in a single threaded process (node) is just asking for trouble, and few get beyond the terrible experience with `node-speaker` and the `mpg123` backend.

Even @TooTallNate threw up his hands about this - the only way to get a robust solution is to also fork the more modern `libao` or `portaudio` in the `node-speaker` package, which already forks `mpg123`. Way too much maintenance overhead. It is stuck with `mpg123` (which is mature but hard to configure).

Thanks for the advice, I am weighing the cost of migrating (but I just passed all my testing with `node-speaker`!) It can also use `libao` as a backend assuming it's installed, which I can't. `naudion` claims to have no dependencies/pre-reqs since it includes a fork of `portaudio` so we may have a  winner.

**Comment by colinbdclark** [comment]
I don't think it's so much the case of it being "asking for trouble" to do robust audio in a single thread. If you look more closely at the implementations of most of these libraries, you will see that they do indeed output audio in a separate, real-time thread using whichever backend library they've chosen. However, I think there is a quality of implementation issue at play here, and perhaps most people aren't doing intensive audio work on Node.js. The Web Audio implementations in Chrome and Firefox are evidence that highly robust audio implementations can be built in so-called single-threaded, event-based environments. It's just that most of the Node.js modules seem to be of much poorer quality (which is why I ultimately switched to using Electron or headless Chrome for these kinds of things).

Perhaps the size of the user base shouldn't, in this case, be your main metric for choosing a library? <code>naudiodon</code> could be a good choice. Let me know if it ends up working for you, I'm curious.

Best of luck!

**Comment by dcerisano** [comment]
I found calling the audio libraries too quickly directly from node was problematic, forcing me to spawn a dedicated audio thread. Of course then I found that the spawned thread behaved differently on Windows, closing after each call. I am sticking with your library, since it works well on all platforms, and mpg123 is at least mature. The large user base is how I found your library. Latency was my top metric, with support always a close second. Don't want to go down another rabbit-hole with a different library. Thanks again!

Node is great at streaming audio and video to media clients, but playing media on a server directly is a very wonky use case, and yes not terribly well  implemented or documented.

**Pull request closed without merging**
